/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clearancems;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Jed
 */
public class ClearanceRequestForm extends javax.swing.JFrame {
    private int studentID;
    private String idno;
    private String fullname;
    private String course;
    private ButtonGroup semFilterGroup; // For the semester filter radio buttons

    
   

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClearanceRequestForm.class.getName());

    /**
     * Creates new form ClearanceRequestForm
     */
    
    public ClearanceRequestForm(int studentID, String idno, String fullname, String course) {
        initComponents();
        setLocationRelativeTo(null);
        firstsemrequestrdobtn1.addActionListener(e -> FilterByAYSem());
        secondsemrequestrdobtn1.addActionListener(e -> FilterByAYSem());
        
   // table will be empty at startup
        semFilterGroup = new ButtonGroup();
    semFilterGroup.add(firstsemrequestrdobtn1);
    semFilterGroup.add(secondsemrequestrdobtn1);
        
     
        
    this.studentID = studentID;
    this.idno = idno;
    this.fullname = fullname;
    this.course = course;
        
        
    idnumbertxtbx.setText(idno);
    fullnametxtbx.setText(fullname);
    coursetxtbx.setText(course);
    
   
        GetClearanceRequest();
        GetAYSem();    
        // after GetAYSem();
acadyearcmbbx2.addActionListener(new java.awt.event.ActionListener() {
    @Override
    public void actionPerformed(java.awt.event.ActionEvent e) {
        FilterByAYSem();
    }
});

// Optionally auto-load the first item if present:
if (acadyearcmbbx2.getItemCount() > 0) {
    // set selected index (0 will be first element from your query)
    acadyearcmbbx2.setSelectedIndex(0);
    // call filter once to show the data for that selection immediately
    
}

    }
    

    private void GetAYSem() {
    try (Connection conn = DBConnection.getConnection()) {
        String query = "SELECT DISTINCT t1.acadyear FROM clearancerequest t1 WHERE t1.studentID=? ORDER BY t1.acadyear DESC;";
        PreparedStatement checkpst = conn.prepareStatement(query);
        checkpst.setInt(1, studentID);
        ResultSet rs = checkpst.executeQuery();

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("All");

        while (rs.next()) {
            String acadyear = rs.getString("acadyear");
            model.addElement(acadyear);
        }

        acadyearcmbbx2.setModel(model);

        rs.close();
        checkpst.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading academic years: " + e.getMessage());
    }
}

    
        
        
        
    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup2 = new javax.swing.ButtonGroup();
        ButtonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        signoutbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idnumbertxtbx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fullnametxtbx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        coursetxtbx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        acadyearcmbbx = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        firstsemrequestrdobtn = new javax.swing.JRadioButton();
        secondsemrequestrdobtn = new javax.swing.JRadioButton();
        submitrequestbtn = new javax.swing.JButton();
        cancelrequestbtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        acadyearcmbbx2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        firstsemrequestrdobtn1 = new javax.swing.JRadioButton();
        secondsemrequestrdobtn1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        clearancestatusIDlbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1120, 525));

        jPanel5.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLEARANCE MANAGEMENT SYSTEM");

        signoutbtn.setBackground(new java.awt.Color(153, 153, 153));
        signoutbtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        signoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        signoutbtn.setText("Sign Out");
        signoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signoutbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Manage Request Form");

        jLabel3.setText("ID Number:");

        idnumbertxtbx.setEnabled(false);

        jLabel4.setText("Full Name:");

        fullnametxtbx.setEnabled(false);

        jLabel5.setText("Course:");

        coursetxtbx.setEnabled(false);

        jLabel6.setText("Academic Year:");

        acadyearcmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select AY", "2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025", "2025-2026", "2026-2027", "2027-2028" }));

        jLabel7.setText("Semester:");

        firstsemrequestrdobtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        firstsemrequestrdobtn.setText("First Sem");
        firstsemrequestrdobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstsemrequestrdobtnMouseClicked(evt);
            }
        });

        secondsemrequestrdobtn.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        secondsemrequestrdobtn.setText("Second Sem");
        secondsemrequestrdobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondsemrequestrdobtnMouseClicked(evt);
            }
        });

        submitrequestbtn.setBackground(new java.awt.Color(0, 0, 102));
        submitrequestbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitrequestbtn.setForeground(new java.awt.Color(255, 255, 255));
        submitrequestbtn.setText("Submit Request");
        submitrequestbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitrequestbtnMouseClicked(evt);
            }
        });
        submitrequestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitrequestbtnActionPerformed(evt);
            }
        });

        cancelrequestbtn.setBackground(new java.awt.Color(153, 153, 153));
        cancelrequestbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelrequestbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelrequestbtn.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idnumbertxtbx)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fullnametxtbx)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coursetxtbx)
                    .addComponent(acadyearcmbbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstsemrequestrdobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(secondsemrequestrdobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(submitrequestbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelrequestbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idnumbertxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fullnametxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coursetxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acadyearcmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(firstsemrequestrdobtn)
                    .addComponent(secondsemrequestrdobtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitrequestbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelrequestbtn)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Academic year:");

        acadyearcmbbx2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select AY", "2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025", "2025-2026", "2026-2027", "2027-2028" }));
        acadyearcmbbx2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acadyearcmbbx2MouseClicked(evt);
            }
        });
        acadyearcmbbx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acadyearcmbbx2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Semester:");

        firstsemrequestrdobtn1.setText("First Sem:");
        firstsemrequestrdobtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstsemrequestrdobtn1MouseClicked(evt);
            }
        });

        secondsemrequestrdobtn1.setText("Second Sem");
        secondsemrequestrdobtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondsemrequestrdobtn1MouseClicked(evt);
            }
        });

        clearancestatusIDlbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(clearancestatusIDlbl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(acadyearcmbbx2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel9)
                        .addGap(14, 14, 14)
                        .addComponent(firstsemrequestrdobtn1)
                        .addGap(18, 18, 18)
                        .addComponent(secondsemrequestrdobtn1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(acadyearcmbbx2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(firstsemrequestrdobtn1)
                            .addComponent(secondsemrequestrdobtn1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstsemrequestrdobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstsemrequestrdobtnMouseClicked
        firstsemrequestrdobtn.setSelected(true);
        secondsemrequestrdobtn.setSelected(false);        
    }//GEN-LAST:event_firstsemrequestrdobtnMouseClicked

    private void secondsemrequestrdobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondsemrequestrdobtnMouseClicked
firstsemrequestrdobtn.setSelected(false);
        secondsemrequestrdobtn.setSelected(true);        
    }//GEN-LAST:event_secondsemrequestrdobtnMouseClicked

    private void signoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutbtnMouseClicked
        SignInForm log = new SignInForm();
        log.setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_signoutbtnMouseClicked

    private void firstsemrequestrdobtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstsemrequestrdobtn1MouseClicked
firstsemrequestrdobtn1.setSelected(true);
    secondsemrequestrdobtn1.setSelected(false);
  
          // TODO add your handling code here:
    }//GEN-LAST:event_firstsemrequestrdobtn1MouseClicked

    private void secondsemrequestrdobtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondsemrequestrdobtn1MouseClicked
        firstsemrequestrdobtn1.setSelected(false);
    secondsemrequestrdobtn1.setSelected(true);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_secondsemrequestrdobtn1MouseClicked

    private void submitrequestbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitrequestbtnMouseClicked
if (acadyearcmbbx.getSelectedIndex()==0 || (!firstsemrequestrdobtn.isSelected() && !secondsemrequestrdobtn.isSelected())) {
    JOptionPane.showMessageDialog(this,"Please fill out all fields.","Information",JOptionPane.WARNING_MESSAGE);
    idnumbertxtbx.requestFocus();
    fullnametxtbx.requestFocus();
    coursetxtbx.requestFocus();
    acadyearcmbbx.requestFocus();
}else{
    String semester = "";
    if (firstsemrequestrdobtn.isSelected()) {
        semester = "First Sem";
    } else if (secondsemrequestrdobtn.isSelected()) {
        semester = "Second Sem";
    }
    try (Connection conn = DBConnection.getConnection()) {
        //CHECK IF STUDENT ALREADY REQUEST WITH THE SAME ACADEMIC YEAR AND SEMESTER
        String checkquery = "Select * FROM `clearancerequest` WHERE studentID=? AND acadyear=? AND semester=? LIMIT 1";
        PreparedStatement checkpst = conn.prepareStatement(checkquery);
        checkpst.setInt(1, studentID);
        checkpst.setString(2, acadyearcmbbx.getSelectedItem().toString());
        checkpst.setString(3, semester);
        ResultSet rs = checkpst.executeQuery();
        if (rs.next()) {
            //Student have already requested with the same acadyear and semester
            JOptionPane.showMessageDialog(this,"You cannot proceed-a request for the same academic year and semester already exists.",
                    "Information",JOptionPane.WARNING_MESSAGE);
        } else {
            //INSERT REQUEST
            String insertQuery = "INSERT INTO `clearancerequest`(`studentID`, `acadyear`, `semester`, `dateRequested`) "
                    + "VALUES (?,?,?,NOW())";
            PreparedStatement psrequest = conn.prepareStatement(insertQuery, Statement.RETURN_GENERATED_KEYS);
            psrequest.setInt(1, studentID);
            psrequest.setString(2, acadyearcmbbx.getSelectedItem().toString());
            psrequest.setString(3, semester);
            psrequest.executeUpdate();

            ResultSet getrs = psrequest.getGeneratedKeys();
            int clearancerequestID = 0;
            if (getrs.next()) {
                clearancerequestID = getrs.getInt(1);
            }
            psrequest.close();

            //GET CLEARING OFFICES
            String getquery = "Select * FROM `clearingoffices`";
            PreparedStatement pstClearOffice = conn.prepareStatement(getquery);
            ResultSet clearingofficers = pstClearOffice.executeQuery();

            //INSERT CLEARING OFFICES ALONG WITH CLEARANCE REQUESTID
            String sqlclearancestatus = "INSERT INTO clearancestatus (clearancerequestID, clearingofficesID, status) VALUES (?,?,?)";
            PreparedStatement psstatus = conn.prepareStatement(sqlclearancestatus);
            while(clearingofficers.next()){
                int clearingofficeID=clearingofficers.getInt("clearingofficesID");

                psstatus.setInt(1, clearancerequestID);
                psstatus.setInt(2, clearingofficeID);
                psstatus.setString(3, "Pending");
                psstatus.executeUpdate();
            }
            clearfields();
            GetClearanceRequest();
            GetAYSem(); // Refresh AY combo box
            acadyearcmbbx2.setSelectedItem("All"); // Show all records by default
            FilterByAYSem(); // Refresh the table according to current filter

            JOptionPane.showMessageDialog(this,"Clearance Request has been submitted to offices.","Information",
        JOptionPane.INFORMATION_MESSAGE);


            

        }
    }catch(SQLException ae){
        JOptionPane.showMessageDialog(this, "Error!", "Information", JOptionPane.WARNING_MESSAGE);

    }
}

    }//GEN-LAST:event_submitrequestbtnMouseClicked

    private void acadyearcmbbx2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acadyearcmbbx2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_acadyearcmbbx2MouseClicked

    private void acadyearcmbbx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acadyearcmbbx2ActionPerformed
String selectedAY = acadyearcmbbx2.getSelectedItem() != null ? acadyearcmbbx2.getSelectedItem().toString() : "";

    if ("All".equals(selectedAY)) {
        if (semFilterGroup != null) {
            semFilterGroup.clearSelection();
        }
    }

    // Continue filtering
    FilterByAYSem();

          
// TODO add your handling code here:
    }//GEN-LAST:event_acadyearcmbbx2ActionPerformed

    private void submitrequestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitrequestbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submitrequestbtnActionPerformed

    // === ADD BELOW ===
                                          

// --- Add this method to your class ---
private void FilterByAYSem() {
    try (Connection conn = DBConnection.getConnection()) {
        String selectedAY = acadyearcmbbx2.getSelectedItem() != null ? acadyearcmbbx2.getSelectedItem().toString() : "";
        String semester = "";

        // Determine selected semester
        if (firstsemrequestrdobtn1.isSelected()) {
            semester = "First Sem";
        } else if (secondsemrequestrdobtn1.isSelected()) {
            semester = "Second Sem";
        }

        // Build base query
        StringBuilder query = new StringBuilder(
            "SELECT t3.clearingoffice, CONCAT(t1.acadyear,'-',t1.semester) AS aysem, " +
            "t2.status, t2.remarks, t1.dateRequested " +
            "FROM clearancerequest AS t1 " +
            "LEFT JOIN clearancestatus AS t2 ON t1.clearancerequestID = t2.clearancerequestID " +
            "JOIN clearingoffices AS t3 ON t3.clearingofficesID = t2.clearingofficesID " +
            "WHERE t1.studentID = ?"
        );

        // Add conditions dynamically
        if (!"All".equals(selectedAY)) {
            query.append(" AND t1.acadyear = ?");
        }
        if (!semester.isEmpty()) {
            query.append(" AND t1.semester = ?");
        }

        query.append(" ORDER BY t1.dateRequested DESC;");

        PreparedStatement pst = conn.prepareStatement(query.toString());
        int paramIndex = 1;
        pst.setInt(paramIndex++, studentID);
        if (!"All".equals(selectedAY)) pst.setString(paramIndex++, selectedAY);
        if (!semester.isEmpty()) pst.setString(paramIndex++, semester);

        ResultSet rs = pst.executeQuery();

        // Prepare table model
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel();
        model.addColumn("Clearing Offices");
        model.addColumn("Academic Year and Sem");
        model.addColumn("Status");
        model.addColumn("Remarks");
        model.addColumn("Date Requested");

        boolean hasData = false;
        while (rs.next()) {
            hasData = true;
            model.addRow(new Object[]{
                rs.getString("clearingoffice"),
                rs.getString("aysem"),
                rs.getString("status"),
                rs.getString("remarks"),
                rs.getString("dateRequested")
            });
        }

        if (!hasData) {
            model.addRow(new Object[]{"No data found", "", "", "", ""});
        }

        clearancestatusIDlbl.setModel(model);
        rs.close();
        pst.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error filtering data: " + ex.getMessage(),
                "Database Error", JOptionPane.WARNING_MESSAGE);
    }
}







    
private void clearfields(){
    acadyearcmbbx.setSelectedIndex(0);
    firstsemrequestrdobtn.setSelected(false);
    secondsemrequestrdobtn.setSelected(false);
           
}

public void GetClearanceRequest() {
    try (Connection conn = DBConnection.getConnection()) {
        String query = "SELECT *, concat(t1.acadyear,'-',t1.semester) as aysem "
                     + "FROM clearancerequest as t1 "
                     + "LEFT JOIN clearancestatus as t2 ON t1.clearancerequestID=t2.clearancerequestID "
                     + "JOIN clearingoffices as t3 ON t3.clearingofficesID=t2.clearingofficesID "
                     + "WHERE t1.studentID=?";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setInt(1, studentID);
        ResultSet rs = pst.executeQuery();

        // Create table model
        DefaultTableModel col = new DefaultTableModel();
        col.addColumn("Clearing Offices");
        col.addColumn("Academic Year and Sem");
        col.addColumn("Status");
        col.addColumn("Remarks");
        col.addColumn("Date Requested");

        // Populate table rows
        while (rs.next()) {
            col.addRow(new Object[]{
                rs.getString("clearingoffice"),
                rs.getString("aysem"),
                rs.getString("status"),
                rs.getString("remarks"),
                rs.getString("dateRequested")
            });
        }

        // Set model to table
        clearancestatusIDlbl.setModel(col);

        // Instruction Step 4: Apply row coloring based on Status
        clearancestatusIDlbl.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String status = table.getValueAt(row, 2) != null ? table.getValueAt(row, 2).toString() : "";
                if (!isSelected) { 
                    if (status.equalsIgnoreCase("Cleared")) {
                        c.setBackground(Color.GREEN);
                        c.setForeground(Color.BLACK); // make text readable
                    } else {
                        c.setBackground(Color.WHITE);
                        c.setForeground(Color.BLACK);
                    }
                }
                return c;
            }
        });

        rs.close();
        pst.close();
        conn.close();

    } catch (SQLException ae) {
        JOptionPane.showMessageDialog(this, "Error!", "Information", JOptionPane.WARNING_MESSAGE);
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroup1;
    private javax.swing.ButtonGroup ButtonGroup2;
    private javax.swing.JComboBox<String> acadyearcmbbx;
    private javax.swing.JComboBox<String> acadyearcmbbx2;
    private javax.swing.JButton cancelrequestbtn;
    private javax.swing.JTable clearancestatusIDlbl;
    private javax.swing.JTextField coursetxtbx;
    private javax.swing.JRadioButton firstsemrequestrdobtn;
    private javax.swing.JRadioButton firstsemrequestrdobtn1;
    private javax.swing.JTextField fullnametxtbx;
    private javax.swing.JTextField idnumbertxtbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton secondsemrequestrdobtn;
    private javax.swing.JRadioButton secondsemrequestrdobtn1;
    private javax.swing.JButton signoutbtn;
    private javax.swing.JButton submitrequestbtn;
    // End of variables declaration//GEN-END:variables
}
