/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clearancems;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Jed
 */
public class RegistrationForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegistrationForm.class.getName());

    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idnumbertxtbx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fullnametxtbx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        coursecmbbx = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        malerdobtn = new javax.swing.JRadioButton();
        femalerdobtn = new javax.swing.JRadioButton();
        cancelbtn = new javax.swing.JButton();
        registerbtn = new javax.swing.JButton();
        signinlink = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        usernametxtbx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordtxtbx = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLEARANCE MANAGEMENT SYSTEM");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(370, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REGISTRATION FORM");

        jLabel3.setText("ID Number:");

        idnumbertxtbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumbertxtbxActionPerformed(evt);
            }
        });

        jLabel4.setText("Full Name:");
        jLabel4.setPreferredSize(new java.awt.Dimension(61, 16));

        jLabel5.setText("Course:");

        coursecmbbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "BSIT", "BSCE", "BSMRS", "BSM", "BITM" }));

        jLabel6.setText("Gender:");

        malerdobtn.setText("Male");
        malerdobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                malerdobtnMouseClicked(evt);
            }
        });
        malerdobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malerdobtnActionPerformed(evt);
            }
        });

        femalerdobtn.setText("Female");
        femalerdobtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                femalerdobtnMouseClicked(evt);
            }
        });

        cancelbtn.setBackground(new java.awt.Color(204, 204, 204));
        cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cancelbtn.setText("Cancel");
        cancelbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelbtnMouseClicked(evt);
            }
        });

        registerbtn.setBackground(new java.awt.Color(0, 0, 102));
        registerbtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerbtn.setForeground(new java.awt.Color(255, 255, 255));
        registerbtn.setText("Register");
        registerbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbtnMouseClicked(evt);
            }
        });
        registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbtnActionPerformed(evt);
            }
        });

        signinlink.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        signinlink.setText("Already have an account? Click here to signin");
        signinlink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinlinkMouseClicked(evt);
            }
        });

        jLabel8.setText("Username:");

        jLabel9.setText("Password:");

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Enter your school credentials");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Create your login credentials");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(malerdobtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femalerdobtn))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fullnametxtbx)
                                                .addComponent(idnumbertxtbx)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(coursecmbbx, 0, 250, Short.MAX_VALUE))
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(usernametxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(passwordtxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 18, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(signinlink))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idnumbertxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fullnametxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordtxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coursecmbbx, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(malerdobtn)
                            .addComponent(femalerdobtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(usernametxtbx, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signinlink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idnumbertxtbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumbertxtbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumbertxtbxActionPerformed

    private void malerdobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malerdobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_malerdobtnActionPerformed

    private void registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerbtnActionPerformed

    private void malerdobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_malerdobtnMouseClicked
     malerdobtn.setSelected(true);
     femalerdobtn.setSelected(false);    
    }//GEN-LAST:event_malerdobtnMouseClicked

    private void femalerdobtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_femalerdobtnMouseClicked
    malerdobtn.setSelected(false);
     femalerdobtn.setSelected(true);             // TODO add your handling code here:
    }//GEN-LAST:event_femalerdobtnMouseClicked

    private void signinlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinlinkMouseClicked
    SignInForm log = new SignInForm();
    log.setVisible(true);
    this.dispose();  
    }//GEN-LAST:event_signinlinkMouseClicked

    private void cancelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelbtnMouseClicked
    clearForm();        
    }//GEN-LAST:event_cancelbtnMouseClicked

    private void registerbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbtnMouseClicked
if(idnumbertxtbx.getText().trim().length() > 9 ||idnumbertxtbx.getText().trim().length() < 9 ) {
                JOptionPane.showMessageDialog(this, "Invalid Id format", "Information", JOptionPane.WARNING_MESSAGE);
                return;
            }
        if (idnumbertxtbx.getText().trim().isEmpty() || fullnametxtbx.getText().trim().isEmpty() ||
            coursecmbbx.getSelectedIndex() == 0 || (!malerdobtn.isSelected() && !femalerdobtn.isSelected())||
             usernametxtbx.getText().trim().isEmpty() || passwordtxtbx.getPassword().length == 0 ) {
            JOptionPane.showMessageDialog(this,"Please Fill out all the Forms" , "Information", JOptionPane.WARNING_MESSAGE);
        }else {
            
            // Akoa ni
            try (Connection con = DBConnection.getConnection()){
                String checkusername = """
                                       SELECT * FROM user 
                                       WHERE username =  AES_ENCRYPT(?, 'V0dG8`C13-yp');
                                       """;
                
                PreparedStatement checkuser = con.prepareStatement(checkusername);
                checkuser.setString(1, usernametxtbx.getText().trim());
                ResultSet rs = checkuser.executeQuery();
                if(rs.next()) {
                    JOptionPane.showMessageDialog(this, "This username\n" + usernametxtbx.getText().trim()  + "\nAlready exists" , "Information", JOptionPane.ERROR_MESSAGE);
                    clearForm();
                    return;
                }
            }catch (Exception e) {
                e.printStackTrace();
            }
            
            try (Connection conn = DBConnection.getConnection()){                   
                String checkquerry = "SELECT * FROM student WHERE idno = ?";
                PreparedStatement checkpst = conn.prepareStatement(checkquerry);
                checkpst.setString(1, idnumbertxtbx.getText().trim());
                ResultSet rs = checkpst.executeQuery();    
                if(rs.next()) {
                    JOptionPane.showMessageDialog(this, "User already exists","Information", JOptionPane.WARNING_MESSAGE);
                }else {
                    String sqlUser = "INSERT INTO user (fullname, username, password, type) VALUES (?, AES_ENCRYPT(?, 'V0dG8`C13-yp'), AES_ENCRYPT(?, 'V0dG8`C13-yp'),?)";
                    PreparedStatement psUser = conn.prepareStatement(sqlUser, Statement.RETURN_GENERATED_KEYS);
                    psUser.setString(1, fullnametxtbx.getText().trim());
                    psUser.setString(2, usernametxtbx.getText().trim());
                    psUser.setString(3, new String(passwordtxtbx.getPassword()));
                    psUser.setString(4, "student");
                    psUser.executeUpdate();                   
                    
                    ResultSet getrs = psUser.getGeneratedKeys();
                    int userID = 0;
                    if(getrs.next()) {
                        userID = getrs.getInt(1);
                    }
                    
                    String gender = "";
                    if(malerdobtn.isSelected()) {
                        gender = "Male";
                    }else if(femalerdobtn.isSelected()) {
                        gender = "Female";
                    }
                    
                    String sqlStudent = "INSERT INTO student(userID, idno, fullname, course, gender, dateRegistered) VALUES (?,?,?,?,?, NOW())";
                    PreparedStatement psStudent = conn.prepareStatement(sqlStudent);
                    psStudent.setInt(1, userID);
                    psStudent.setString(2,idnumbertxtbx.getText().trim());
                    psStudent.setString(3, fullnametxtbx.getText().trim());
                    psStudent.setString(4,coursecmbbx.getSelectedItem().toString());
                    psStudent.setString(5, gender);
                    psStudent.executeUpdate();
                    
                    clearForm();
                    
                    JOptionPane.showMessageDialog(this, "Registered Succesfully", "Information",JOptionPane.INFORMATION_MESSAGE);
                   
                }
            }catch (SQLException e) {
                e.printStackTrace();
                System.out.println("Error!!");
            }
        }       
    }//GEN-LAST:event_registerbtnMouseClicked
    
    private void clearForm() {
        idnumbertxtbx.setText("");
        fullnametxtbx.setText("");
        coursecmbbx.setSelectedIndex(0);
        malerdobtn.setSelected(false);
        femalerdobtn.setSelected(false);
        usernametxtbx.setText("");
        passwordtxtbx.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegistrationForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelbtn;
    private javax.swing.JComboBox<String> coursecmbbx;
    private javax.swing.JRadioButton femalerdobtn;
    private javax.swing.JTextField fullnametxtbx;
    private javax.swing.JTextField idnumbertxtbx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton malerdobtn;
    private javax.swing.JPasswordField passwordtxtbx;
    private javax.swing.JButton registerbtn;
    private javax.swing.JLabel signinlink;
    private javax.swing.JTextField usernametxtbx;
    // End of variables declaration//GEN-END:variables
}
